name: Build Kernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Set up Android NDK
      uses: android-actions/setup-android@v2
      with:
        ndk-version: '21.3.6528147'

    - name: Set up ARM toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabi make

    - name: Build Kernel
      run: |
        export CROSS_COMPILE==${PWD}arm-linux-androideabi-4.9/bin/arm-linux-androidkernel-
        export ARCH=arm
        make O=OUT/5059D/ ARCH=arm CROSS_COMPILE=$CROSS_COMPILE u5a_plus_4g_odm_defconfig
        make O=OUT/5059D/ ARCH=arm CROSS_COMPILE=$CROSS_COMPILE -j2
